/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  photographerName?: string;
  seoTitleIt?: string;
  seoTitleEn?: string;
  seoDescriptionIt?: string;
  seoDescriptionEn?: string;
  socialImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  email?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bioIt?: string;
  bioEn?: string;
  statementIt?: string;
  statementEn?: string;
  email?: string;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
};

export type PhotoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "photo";
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroPhoto?: PhotoReference;
  introIt?: string;
  introEn?: string;
  selectedPhotos?: Array<
    {
      _key: string;
    } & PhotoReference
  >;
  selectedProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titleIt?: string;
  titleEn?: string;
  descriptionIt?: string;
  descriptionEn?: string;
  slug?: Slug;
  year?: number;
  cover?: PhotoReference;
  photos?: Array<
    {
      _key: string;
    } & PhotoReference
  >;
  featured?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Photo = {
  _id: string;
  _type: "photo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  altIt?: string;
  altEn?: string;
  titleIt?: string;
  titleEn?: string;
  placeIt?: string;
  placeEn?: string;
  year?: number;
  showInGallery?: boolean;
  orderRank?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | AboutPage
  | PhotoReference
  | ProjectReference
  | HomePage
  | Project
  | Slug
  | Photo
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/sanity/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]{    photographerName,    seoTitleIt, seoTitleEn,    seoDescriptionIt, seoDescriptionEn,    email,    "socialImageUrl": socialImage.asset->url  }
export type SiteSettingsQueryResult = {
  photographerName: string | null;
  seoTitleIt: string | null;
  seoTitleEn: string | null;
  seoDescriptionIt: string | null;
  seoDescriptionEn: string | null;
  email: string | null;
  socialImageUrl: string | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage"][0]{    introIt, introEn  }
export type HomePageQueryResult = {
  introIt: string | null;
  introEn: string | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: galleryPageQuery
// Query: *[_type == "photo" && showInGallery == true && defined(image.asset)]    | order(orderRank asc)[$start...$end]{  _id,  altIt, altEn,  titleIt, titleEn,  placeIt, placeEn,  year,  "url": image.asset->url,  "aspectRatio": image.asset->metadata.dimensions.aspectRatio,  "lqip": image.asset->metadata.lqip}
export type GalleryPageQueryResult = Array<{
  _id: string;
  altIt: string | null;
  altEn: string | null;
  titleIt: string | null;
  titleEn: string | null;
  placeIt: string | null;
  placeEn: string | null;
  year: number | null;
  url: string | null;
  aspectRatio: number | null;
  lqip: string | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: galleryCountQuery
// Query: count(*[_type == "photo" && showInGallery == true && defined(image.asset)])
export type GalleryCountQueryResult = number;

// Source: lib/sanity/queries.ts
// Variable: homeHeroQuery
// Query: *[_type == "homePage"][0]{    introIt, introEn,    "heroPhoto": heroPhoto->{  _id,  altIt, altEn,  titleIt, titleEn,  placeIt, placeEn,  year,  "url": image.asset->url,  "aspectRatio": image.asset->metadata.dimensions.aspectRatio,  "lqip": image.asset->metadata.lqip}  }
export type HomeHeroQueryResult = {
  introIt: string | null;
  introEn: string | null;
  heroPhoto: {
    _id: string;
    altIt: string | null;
    altEn: string | null;
    titleIt: string | null;
    titleEn: string | null;
    placeIt: string | null;
    placeEn: string | null;
    year: number | null;
    url: string | null;
    aspectRatio: number | null;
    lqip: string | null;
  } | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: aboutPageQuery
// Query: *[_type == "aboutPage"][0]{    bioIt, bioEn,    statementIt, statementEn,    email,    socialLinks[]{label, url},    "portraitUrl": portrait.asset->url,    "portraitAr": portrait.asset->metadata.dimensions.aspectRatio,    "portraitLqip": portrait.asset->metadata.lqip  }
export type AboutPageQueryResult = {
  bioIt: string | null;
  bioEn: string | null;
  statementIt: string | null;
  statementEn: string | null;
  email: string | null;
  socialLinks: Array<{
    label: string | null;
    url: string | null;
  }> | null;
  portraitUrl: string | null;
  portraitAr: number | null;
  portraitLqip: string | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: projectsIndexQuery
// Query: *[_type == "project" && defined(slug.current)] | order(year desc, titleIt asc){    _id,    titleIt, titleEn,    year,    "slug": slug.current,    "cover": cover->{  _id,  altIt, altEn,  titleIt, titleEn,  placeIt, placeEn,  year,  "url": image.asset->url,  "aspectRatio": image.asset->metadata.dimensions.aspectRatio,  "lqip": image.asset->metadata.lqip}  }
export type ProjectsIndexQueryResult = Array<{
  _id: string;
  titleIt: string | null;
  titleEn: string | null;
  year: number | null;
  slug: string | null;
  cover: {
    _id: string;
    altIt: string | null;
    altEn: string | null;
    titleIt: string | null;
    titleEn: string | null;
    placeIt: string | null;
    placeEn: string | null;
    year: number | null;
    url: string | null;
    aspectRatio: number | null;
    lqip: string | null;
  } | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: projectBySlugQuery
// Query: *[_type == "project" && slug.current == $slug][0]{    _id,    titleIt, titleEn,    descriptionIt, descriptionEn,    year,    "slug": slug.current,    "cover": cover->{  _id,  altIt, altEn,  titleIt, titleEn,  placeIt, placeEn,  year,  "url": image.asset->url,  "aspectRatio": image.asset->metadata.dimensions.aspectRatio,  "lqip": image.asset->metadata.lqip},    "photos": photos[defined(@->)]->{  _id,  altIt, altEn,  titleIt, titleEn,  placeIt, placeEn,  year,  "url": image.asset->url,  "aspectRatio": image.asset->metadata.dimensions.aspectRatio,  "lqip": image.asset->metadata.lqip}  }
export type ProjectBySlugQueryResult = {
  _id: string;
  titleIt: string | null;
  titleEn: string | null;
  descriptionIt: string | null;
  descriptionEn: string | null;
  year: number | null;
  slug: string | null;
  cover: {
    _id: string;
    altIt: string | null;
    altEn: string | null;
    titleIt: string | null;
    titleEn: string | null;
    placeIt: string | null;
    placeEn: string | null;
    year: number | null;
    url: string | null;
    aspectRatio: number | null;
    lqip: string | null;
  } | null;
  photos: Array<{
    _id: string;
    altIt: string | null;
    altEn: string | null;
    titleIt: string | null;
    titleEn: string | null;
    placeIt: string | null;
    placeEn: string | null;
    year: number | null;
    url: string | null;
    aspectRatio: number | null;
    lqip: string | null;
  }> | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: projectSlugsQuery
// Query: *[_type == "project" && defined(slug.current)].slug.current
export type ProjectSlugsQueryResult = Array<string | null>;

// Source: lib/sanity/queries.ts
// Variable: sitemapQuery
// Query: {  "projects": *[_type == "project" && defined(slug.current)]{    "slug": slug.current,    _updatedAt  },  "settingsUpdatedAt": *[_type == "siteSettings"][0]._updatedAt}
export type SitemapQueryResult = {
  projects: Array<{
    slug: string | null;
    _updatedAt: string;
  }>;
  settingsUpdatedAt: string | null;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0]{\n    photographerName,\n    seoTitleIt, seoTitleEn,\n    seoDescriptionIt, seoDescriptionEn,\n    email,\n    "socialImageUrl": socialImage.asset->url\n  }\n': SiteSettingsQueryResult;
    '\n  *[_type == "homePage"][0]{\n    introIt, introEn\n  }\n': HomePageQueryResult;
    '\n  *[_type == "photo" && showInGallery == true && defined(image.asset)]\n    | order(orderRank asc)[$start...$end]{\n  _id,\n  altIt, altEn,\n  titleIt, titleEn,\n  placeIt, placeEn,\n  year,\n  "url": image.asset->url,\n  "aspectRatio": image.asset->metadata.dimensions.aspectRatio,\n  "lqip": image.asset->metadata.lqip\n}\n': GalleryPageQueryResult;
    '\n  count(*[_type == "photo" && showInGallery == true && defined(image.asset)])\n': GalleryCountQueryResult;
    '\n  *[_type == "homePage"][0]{\n    introIt, introEn,\n    "heroPhoto": heroPhoto->{\n  _id,\n  altIt, altEn,\n  titleIt, titleEn,\n  placeIt, placeEn,\n  year,\n  "url": image.asset->url,\n  "aspectRatio": image.asset->metadata.dimensions.aspectRatio,\n  "lqip": image.asset->metadata.lqip\n}\n  }\n': HomeHeroQueryResult;
    '\n  *[_type == "aboutPage"][0]{\n    bioIt, bioEn,\n    statementIt, statementEn,\n    email,\n    socialLinks[]{label, url},\n    "portraitUrl": portrait.asset->url,\n    "portraitAr": portrait.asset->metadata.dimensions.aspectRatio,\n    "portraitLqip": portrait.asset->metadata.lqip\n  }\n': AboutPageQueryResult;
    '\n  *[_type == "project" && defined(slug.current)] | order(year desc, titleIt asc){\n    _id,\n    titleIt, titleEn,\n    year,\n    "slug": slug.current,\n    "cover": cover->{\n  _id,\n  altIt, altEn,\n  titleIt, titleEn,\n  placeIt, placeEn,\n  year,\n  "url": image.asset->url,\n  "aspectRatio": image.asset->metadata.dimensions.aspectRatio,\n  "lqip": image.asset->metadata.lqip\n}\n  }\n': ProjectsIndexQueryResult;
    '\n  *[_type == "project" && slug.current == $slug][0]{\n    _id,\n    titleIt, titleEn,\n    descriptionIt, descriptionEn,\n    year,\n    "slug": slug.current,\n    "cover": cover->{\n  _id,\n  altIt, altEn,\n  titleIt, titleEn,\n  placeIt, placeEn,\n  year,\n  "url": image.asset->url,\n  "aspectRatio": image.asset->metadata.dimensions.aspectRatio,\n  "lqip": image.asset->metadata.lqip\n},\n    "photos": photos[defined(@->)]->{\n  _id,\n  altIt, altEn,\n  titleIt, titleEn,\n  placeIt, placeEn,\n  year,\n  "url": image.asset->url,\n  "aspectRatio": image.asset->metadata.dimensions.aspectRatio,\n  "lqip": image.asset->metadata.lqip\n}\n  }\n': ProjectBySlugQueryResult;
    '\n  *[_type == "project" && defined(slug.current)].slug.current\n': ProjectSlugsQueryResult;
    '{\n  "projects": *[_type == "project" && defined(slug.current)]{\n    "slug": slug.current,\n    _updatedAt\n  },\n  "settingsUpdatedAt": *[_type == "siteSettings"][0]._updatedAt\n}': SitemapQueryResult;
  }
}
